#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : json-glib
Version  : 1.8.0
Release  : 38
URL      : https://download.gnome.org/sources/json-glib/1.8/json-glib-1.8.0.tar.xz
Source0  : https://download.gnome.org/sources/json-glib/1.8/json-glib-1.8.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: json-glib-bin = %{version}-%{release}
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-lib = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}
Requires: json-glib-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : gobject-introspection-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
JSON-GLib
===============================================================================

%package bin
Summary: bin components for the json-glib package.
Group: Binaries
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}

%description bin
bin components for the json-glib package.


%package data
Summary: data components for the json-glib package.
Group: Data

%description data
data components for the json-glib package.


%package dev
Summary: dev components for the json-glib package.
Group: Development
Requires: json-glib-lib = %{version}-%{release}
Requires: json-glib-bin = %{version}-%{release}
Requires: json-glib-data = %{version}-%{release}
Provides: json-glib-devel = %{version}-%{release}
Requires: json-glib = %{version}-%{release}

%description dev
dev components for the json-glib package.


%package lib
Summary: lib components for the json-glib package.
Group: Libraries
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}

%description lib
lib components for the json-glib package.


%package license
Summary: license components for the json-glib package.
Group: Default

%description license
license components for the json-glib package.


%package locales
Summary: locales components for the json-glib package.
Group: Default

%description locales
locales components for the json-glib package.


%package tests
Summary: tests components for the json-glib package.
Group: Default
Requires: json-glib = %{version}-%{release}

%description tests
tests components for the json-glib package.


%prep
%setup -q -n json-glib-1.8.0
cd %{_builddir}/json-glib-1.8.0
pushd ..
cp -a json-glib-1.8.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695660377
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
mkdir -p %{buildroot}/usr/share/package-licenses/json-glib
cp %{_builddir}/json-glib-%{version}/COPYING %{buildroot}/usr/share/package-licenses/json-glib/e60c2e780886f95df9c9ee36992b8edabec00bcc || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang json-glib-1.0
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/json-glib-format
/V3/usr/bin/json-glib-validate
/usr/bin/json-glib-format
/usr/bin/json-glib-validate

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Json-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/json-glib-1.0/json-glib/json-builder.h
/usr/include/json-glib-1.0/json-glib/json-enum-types.h
/usr/include/json-glib-1.0/json-glib/json-generator.h
/usr/include/json-glib-1.0/json-glib/json-glib.h
/usr/include/json-glib-1.0/json-glib/json-gobject.h
/usr/include/json-glib-1.0/json-glib/json-gvariant.h
/usr/include/json-glib-1.0/json-glib/json-parser.h
/usr/include/json-glib-1.0/json-glib/json-path.h
/usr/include/json-glib-1.0/json-glib/json-reader.h
/usr/include/json-glib-1.0/json-glib/json-types.h
/usr/include/json-glib-1.0/json-glib/json-utils.h
/usr/include/json-glib-1.0/json-glib/json-version-macros.h
/usr/include/json-glib-1.0/json-glib/json-version.h
/usr/lib64/libjson-glib-1.0.so
/usr/lib64/pkgconfig/json-glib-1.0.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libjson-glib-1.0.so.0.800.0
/usr/lib64/libjson-glib-1.0.so.0
/usr/lib64/libjson-glib-1.0.so.0.800.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/json-glib/e60c2e780886f95df9c9ee36992b8edabec00bcc

%files tests
%defattr(-,root,root,-)
/V3/usr/libexec/installed-tests/json-glib-1.0/array
/V3/usr/libexec/installed-tests/json-glib-1.0/boxed
/V3/usr/libexec/installed-tests/json-glib-1.0/builder
/V3/usr/libexec/installed-tests/json-glib-1.0/generator
/V3/usr/libexec/installed-tests/json-glib-1.0/gvariant
/V3/usr/libexec/installed-tests/json-glib-1.0/invalid
/V3/usr/libexec/installed-tests/json-glib-1.0/node
/V3/usr/libexec/installed-tests/json-glib-1.0/object
/V3/usr/libexec/installed-tests/json-glib-1.0/parser
/V3/usr/libexec/installed-tests/json-glib-1.0/path
/V3/usr/libexec/installed-tests/json-glib-1.0/reader
/V3/usr/libexec/installed-tests/json-glib-1.0/serialize-complex
/V3/usr/libexec/installed-tests/json-glib-1.0/serialize-full
/V3/usr/libexec/installed-tests/json-glib-1.0/serialize-simple
/usr/libexec/installed-tests/json-glib-1.0/array
/usr/libexec/installed-tests/json-glib-1.0/boxed
/usr/libexec/installed-tests/json-glib-1.0/builder
/usr/libexec/installed-tests/json-glib-1.0/generator
/usr/libexec/installed-tests/json-glib-1.0/gvariant
/usr/libexec/installed-tests/json-glib-1.0/invalid
/usr/libexec/installed-tests/json-glib-1.0/invalid.json
/usr/libexec/installed-tests/json-glib-1.0/node
/usr/libexec/installed-tests/json-glib-1.0/object
/usr/libexec/installed-tests/json-glib-1.0/parser
/usr/libexec/installed-tests/json-glib-1.0/path
/usr/libexec/installed-tests/json-glib-1.0/reader
/usr/libexec/installed-tests/json-glib-1.0/serialize-complex
/usr/libexec/installed-tests/json-glib-1.0/serialize-full
/usr/libexec/installed-tests/json-glib-1.0/serialize-simple
/usr/libexec/installed-tests/json-glib-1.0/skip-bom.json
/usr/libexec/installed-tests/json-glib-1.0/stream-load.json
/usr/share/installed-tests/json-glib-1.0/array.test
/usr/share/installed-tests/json-glib-1.0/boxed.test
/usr/share/installed-tests/json-glib-1.0/builder.test
/usr/share/installed-tests/json-glib-1.0/generator.test
/usr/share/installed-tests/json-glib-1.0/gvariant.test
/usr/share/installed-tests/json-glib-1.0/invalid.test
/usr/share/installed-tests/json-glib-1.0/node.test
/usr/share/installed-tests/json-glib-1.0/object.test
/usr/share/installed-tests/json-glib-1.0/parser.test
/usr/share/installed-tests/json-glib-1.0/path.test
/usr/share/installed-tests/json-glib-1.0/reader.test
/usr/share/installed-tests/json-glib-1.0/serialize-complex.test
/usr/share/installed-tests/json-glib-1.0/serialize-full.test
/usr/share/installed-tests/json-glib-1.0/serialize-simple.test

%files locales -f json-glib-1.0.lang
%defattr(-,root,root,-)

