#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : json-glib
Version  : 1.6.0
Release  : 29
URL      : https://download.gnome.org/sources/json-glib/1.6/json-glib-1.6.0.tar.xz
Source0  : https://download.gnome.org/sources/json-glib/1.6/json-glib-1.6.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: json-glib-bin = %{version}-%{release}
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-lib = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}
Requires: json-glib-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev

%description
JSON-GLib
===============================================================================

%package bin
Summary: bin components for the json-glib package.
Group: Binaries
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}

%description bin
bin components for the json-glib package.


%package data
Summary: data components for the json-glib package.
Group: Data

%description data
data components for the json-glib package.


%package dev
Summary: dev components for the json-glib package.
Group: Development
Requires: json-glib-lib = %{version}-%{release}
Requires: json-glib-bin = %{version}-%{release}
Requires: json-glib-data = %{version}-%{release}
Provides: json-glib-devel = %{version}-%{release}
Requires: json-glib = %{version}-%{release}

%description dev
dev components for the json-glib package.


%package doc
Summary: doc components for the json-glib package.
Group: Documentation

%description doc
doc components for the json-glib package.


%package lib
Summary: lib components for the json-glib package.
Group: Libraries
Requires: json-glib-data = %{version}-%{release}
Requires: json-glib-license = %{version}-%{release}

%description lib
lib components for the json-glib package.


%package license
Summary: license components for the json-glib package.
Group: Default

%description license
license components for the json-glib package.


%package locales
Summary: locales components for the json-glib package.
Group: Default

%description locales
locales components for the json-glib package.


%package tests
Summary: tests components for the json-glib package.
Group: Default
Requires: json-glib = %{version}-%{release}

%description tests
tests components for the json-glib package.


%prep
%setup -q -n json-glib-1.6.0
cd %{_builddir}/json-glib-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600274026
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/json-glib
cp %{_builddir}/json-glib-1.6.0/COPYING %{buildroot}/usr/share/package-licenses/json-glib/e60c2e780886f95df9c9ee36992b8edabec00bcc
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang json-glib-1.0

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/json-glib-format
/usr/bin/json-glib-validate

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Json-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/json-glib-1.0/json-glib/json-builder.h
/usr/include/json-glib-1.0/json-glib/json-enum-types.h
/usr/include/json-glib-1.0/json-glib/json-generator.h
/usr/include/json-glib-1.0/json-glib/json-glib.h
/usr/include/json-glib-1.0/json-glib/json-gobject.h
/usr/include/json-glib-1.0/json-glib/json-gvariant.h
/usr/include/json-glib-1.0/json-glib/json-parser.h
/usr/include/json-glib-1.0/json-glib/json-path.h
/usr/include/json-glib-1.0/json-glib/json-reader.h
/usr/include/json-glib-1.0/json-glib/json-types.h
/usr/include/json-glib-1.0/json-glib/json-utils.h
/usr/include/json-glib-1.0/json-glib/json-version-macros.h
/usr/include/json-glib-1.0/json-glib/json-version.h
/usr/lib64/libjson-glib-1.0.so
/usr/lib64/pkgconfig/json-glib-1.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/json-glib/JsonBuilder.html
/usr/share/gtk-doc/html/json-glib/JsonGenerator.html
/usr/share/gtk-doc/html/json-glib/JsonParser.html
/usr/share/gtk-doc/html/json-glib/JsonPath.html
/usr/share/gtk-doc/html/json-glib/JsonReader.html
/usr/share/gtk-doc/html/json-glib/annotation-glossary.html
/usr/share/gtk-doc/html/json-glib/ch01.html
/usr/share/gtk-doc/html/json-glib/ch02.html
/usr/share/gtk-doc/html/json-glib/ch03.html
/usr/share/gtk-doc/html/json-glib/ch04.html
/usr/share/gtk-doc/html/json-glib/ch06.html
/usr/share/gtk-doc/html/json-glib/home.png
/usr/share/gtk-doc/html/json-glib/index.html
/usr/share/gtk-doc/html/json-glib/ix01.html
/usr/share/gtk-doc/html/json-glib/ix02.html
/usr/share/gtk-doc/html/json-glib/ix03.html
/usr/share/gtk-doc/html/json-glib/ix04.html
/usr/share/gtk-doc/html/json-glib/ix05.html
/usr/share/gtk-doc/html/json-glib/ix06.html
/usr/share/gtk-doc/html/json-glib/ix07.html
/usr/share/gtk-doc/html/json-glib/ix08.html
/usr/share/gtk-doc/html/json-glib/ix09.html
/usr/share/gtk-doc/html/json-glib/ix10.html
/usr/share/gtk-doc/html/json-glib/ix11.html
/usr/share/gtk-doc/html/json-glib/ix12.html
/usr/share/gtk-doc/html/json-glib/ix13.html
/usr/share/gtk-doc/html/json-glib/json-advanced.html
/usr/share/gtk-doc/html/json-glib/json-base.html
/usr/share/gtk-doc/html/json-glib/json-format-tool.html
/usr/share/gtk-doc/html/json-glib/json-glib-Boxed-Types-Serialization.html
/usr/share/gtk-doc/html/json-glib/json-glib-GObject-Serialization.html
/usr/share/gtk-doc/html/json-glib/json-glib-JSON-Array.html
/usr/share/gtk-doc/html/json-glib/json-glib-JSON-GVariant-Integration.html
/usr/share/gtk-doc/html/json-glib/json-glib-JSON-Node.html
/usr/share/gtk-doc/html/json-glib/json-glib-JSON-Object.html
/usr/share/gtk-doc/html/json-glib/json-glib-Serializable-Interface.html
/usr/share/gtk-doc/html/json-glib/json-glib-Utility-API.html
/usr/share/gtk-doc/html/json-glib/json-glib-Versioning-information.html
/usr/share/gtk-doc/html/json-glib/json-glib.devhelp2
/usr/share/gtk-doc/html/json-glib/json-overview.html
/usr/share/gtk-doc/html/json-glib/json-streams.html
/usr/share/gtk-doc/html/json-glib/json-tools.html
/usr/share/gtk-doc/html/json-glib/json-validate-tool.html
/usr/share/gtk-doc/html/json-glib/left-insensitive.png
/usr/share/gtk-doc/html/json-glib/left.png
/usr/share/gtk-doc/html/json-glib/license.html
/usr/share/gtk-doc/html/json-glib/right-insensitive.png
/usr/share/gtk-doc/html/json-glib/right.png
/usr/share/gtk-doc/html/json-glib/style.css
/usr/share/gtk-doc/html/json-glib/tools.html
/usr/share/gtk-doc/html/json-glib/up-insensitive.png
/usr/share/gtk-doc/html/json-glib/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjson-glib-1.0.so.0
/usr/lib64/libjson-glib-1.0.so.0.600.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/json-glib/e60c2e780886f95df9c9ee36992b8edabec00bcc

%files tests
%defattr(-,root,root,-)
/usr/libexec/installed-tests/json-glib-1.0/array
/usr/libexec/installed-tests/json-glib-1.0/boxed
/usr/libexec/installed-tests/json-glib-1.0/builder
/usr/libexec/installed-tests/json-glib-1.0/generator
/usr/libexec/installed-tests/json-glib-1.0/gvariant
/usr/libexec/installed-tests/json-glib-1.0/invalid
/usr/libexec/installed-tests/json-glib-1.0/invalid.json
/usr/libexec/installed-tests/json-glib-1.0/node
/usr/libexec/installed-tests/json-glib-1.0/object
/usr/libexec/installed-tests/json-glib-1.0/parser
/usr/libexec/installed-tests/json-glib-1.0/path
/usr/libexec/installed-tests/json-glib-1.0/reader
/usr/libexec/installed-tests/json-glib-1.0/serialize-complex
/usr/libexec/installed-tests/json-glib-1.0/serialize-full
/usr/libexec/installed-tests/json-glib-1.0/serialize-simple
/usr/libexec/installed-tests/json-glib-1.0/stream-load.json
/usr/share/installed-tests/json-glib-1.0/array.test
/usr/share/installed-tests/json-glib-1.0/boxed.test
/usr/share/installed-tests/json-glib-1.0/builder.test
/usr/share/installed-tests/json-glib-1.0/generator.test
/usr/share/installed-tests/json-glib-1.0/gvariant.test
/usr/share/installed-tests/json-glib-1.0/invalid.test
/usr/share/installed-tests/json-glib-1.0/node.test
/usr/share/installed-tests/json-glib-1.0/object.test
/usr/share/installed-tests/json-glib-1.0/parser.test
/usr/share/installed-tests/json-glib-1.0/path.test
/usr/share/installed-tests/json-glib-1.0/reader.test
/usr/share/installed-tests/json-glib-1.0/serialize-complex.test
/usr/share/installed-tests/json-glib-1.0/serialize-full.test
/usr/share/installed-tests/json-glib-1.0/serialize-simple.test

%files locales -f json-glib-1.0.lang
%defattr(-,root,root,-)

